### ISSUE TITLE
npm run dev失败

### ISSUE THREAD

**Issue by beyonderyue** [StellarCN/firefly#109]
### Subject of the issue
Describe your issue here.

### Your environment
MAC os，npm run dev出现错误，是缺少什么东西吗？

 ERROR  Failed to compile with 1 errors                                                                                                               16:39:13

 error  in ./~/awesome-qr/~/canvas/build/Release/canvas.node

Module parse failed: /Users/mobilerover/Documents/GitHub/firefly/node_modules/awesome-qr/node_modules/canvas/build/Release/canvas.node Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

 @ ./~/awesome-qr/~/canvas/lib/bindings.js 3:17-56
 @ ./~/awesome-qr/~/canvas/lib/canvas.js
 @ ./~/awesome-qr/awesome-qr-node.js
 @ ./~/_babel-loader@7.1.4@babel-loader/lib!./src/libs/vue-qr/vue-qr.js
 @ ./src/libs/vue-qr/vue-qr.vue
 @ ./src/libs/vue-qr/main.js
 @ ./~/_babel-loader@7.1.4@babel-loader/lib!./~/_vue-loader@14.2.3@vue-loader/lib/selector.js?type=script&index=0!./src/components/QRCode.vue
 @ ./src/components/QRCode.vue
 @ ./~/_babel-loader@7.1.4@babel-loader/lib!./~/_vue-loader@14.2.3@vue-loader/lib/selector.js?type=script&index=0!./src/pages/contacts/ContactDetails.vue
 @ ./src/pages/contacts/ContactDetails.vue
 @ ./src/router/contacts.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by imloama** [comment]
awesome-qr不建议升级，后续的版本没有兼容npm的环境，强制使用1.0.9版本。

**Comment by imloama** [comment]
另外就是npm的版本不要太高，可以从网上查询下npm编译canvas的问题，需要安装其他的程序，如python2.7 cairo

**Comment by beyonderyue** [comment]
多谢。。
npm现在版本是 5.10.0
不过，npm run cordova又出错了，还请帮忙看看
> firefly@2.1.4 cordova /Users/mobilerover/Documents/GitHub/firefly
> cordova prepare -d

No scripts found for hook "before_prepare".
Checking config.xml and package.json for saved platforms that haven't been added to the project
Config.xml and package.json platforms are the same. No pkg.json modification.
Package.json and config.xml platforms are different. Updating config.xml with most current list of platforms.
Discovered platform "browser@^5.0.1" in config.xml or package.json. Adding it to the project
No scripts found for hook "before_platform_add".
Using cordova-fetch for cordova-browser@^5.0.1
Running command: npm install cordova-browser@^5.0.1 --production --no-save
Command finished with error code 254: npm install,cordova-browser@^5.0.1,--production,--no-save
Error: CordovaError: Failed to fetch platform cordova-browser@^5.0.1
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: npm: Command failed with exit code 254 Error output:
npm WARN onload-script failed to require onload script npm-yaml
npm WARN onload-script Error: Cannot find module 'npm-yaml'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:555:15)
npm WARN onload-script     at Function.Module._load (module.js:482:25)
npm WARN onload-script     at Module.require (module.js:604:17)
npm WARN onload-script     at require (internal/module.js:11:18)
npm WARN onload-script     at cb (/Users/mobilerover/Documents/GitHub/firefly/node_modules/_npm@6.1.0@npm/lib/npm.js:238:11)
npm WARN onload-script     at /Users/mobilerover/Documents/GitHub/firefly/node_modules/_npm@6.1.0@npm/lib/npm.js:373:16
npm WARN onload-script     at /Users/mobilerover/Documents/GitHub/firefly/node_modules/_npm@6.1.0@npm/lib/config/core.js:83:7
npm WARN onload-script     at Array.forEach (<anonymous>)
npm WARN onload-script     at /Users/mobilerover/Documents/GitHub/firefly/node_modules/_npm@6.1.0@npm/lib/config/core.js:82:13
npm WARN onload-script     at f (/Users/mobilerover/Documents/GitHub/firefly/node_modules/_npm@6.1.0@npm/node_modules/once/once.js:25:25)
npm WARN onload-script  { Error: Cannot find module 'npm-yaml'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:555:15)
npm WARN onload-script     at Function.Module._load (module.js:482:25)
npm WARN onload-script     at Module.require (module.js:604:17)
npm WARN onload-script     at require (internal/module.js:11:18)
npm WARN onload-script     at cb (/Users/mobilerover/Documents/GitHub/firefly/node_modules/_npm@6.1.0@npm/lib/npm.js:238:11)
npm WARN onload-script     at /Users/mobilerover/Documents/GitHub/firefly/node_modules/_npm@6.1.0@npm/lib/npm.js:373:16
npm WARN onload-script     at /Users/mobilerover/Documents/GitHub/firefly/node_modules/_npm@6.1.0@npm/lib/config/core.js:83:7
npm WARN onload-script     at Array.forEach (<anonymous>)
npm WARN onload-script     at /Users/mobilerover/Documents/GitHub/firefly/node_modules/_npm@6.1.0@npm/lib/config/core.js:82:13
npm WARN onload-script     at f (/Users/mobilerover/Documents/GitHub/firefly/node_modules/_npm@6.1.0@npm/node_modules/once/once.js:25:25)
npm WARN onload-script   stack: 'Error: Cannot find module \'npm-yaml\'\n    at Function.Module._resolveFilename (module.js:555:15)\n    at Function.Module._load (module.js:482:25)\n    at Module.require (module.js:604:17)\n    at require (internal/module.js:11:18)\n    at cb (/Users/mobilerover/Documents/GitHub/firefly/node_modules/_npm@6.1.0@npm/lib/npm.js:238:11)\n    at /Users/mobilerover/Documents/GitHub/firefly/node_modules/_npm@6.1.0@npm/lib/npm.js:373:16\n    at /Users/mobilerover/Documents/GitHub/firefly/node_modules/_npm@6.1.0@npm/lib/config/core.js:83:7\n    at Array.forEach (<anonymous>)\n    at /Users/mobilerover/Documents/GitHub/firefly/node_modules/_npm@6.1.0@npm/lib/config/core.js:82:13\n    at f (/Users/mobilerover/Documents/GitHub/firefly/node_modules/_npm@6.1.0@npm/node_modules/once/once.js:25:25)',
npm WARN onload-script   code: 'MODULE_NOT_FOUND' }
npm WARN checkPermissions Missing write access to /Users/mobilerover/Documents/GitHub/firefly/node_modules/configstore/node_modules/uuid
npm WARN checkPermissions Missing write access to /Users/mobilerover/Documents/GitHub/firefly/node_modules/got/node_modules/object-assign
npm WARN checkPermissions Missing write access to /Users/mobilerover/Documents/GitHub/firefly/node_modules/har-validator/node_modules/chalk
npm WARN checkPermissions Missing write access to /Users/mobilerover/Documents/GitHub/firefly/node_modules/xmlbuilder/node_modules/lodash
npm WARN checkPermissions Missing write access to /Users/mobilerover/Documents/GitHub/firefly/node_modules/xmlbuilder/node_modules
npm ERR! path /Users/mobilerover/Documents/GitHub/firefly/node_modules/configstore/node_modules/uuid
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/Users/mobilerover/Documents/GitHub/firefly/node_modules/configstore/node_modules/uuid'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by imloama** [comment]
1. cordova版本使用7.1.0 , npm install -g cordova@7.1.0     我测试过8.0版本没通过
2. 你可以尝试清理下node_modules，再重试
3. 因为国内的网络问题，经常会出现错误，这块可以尝试使用cnpm
4. npm run cordova失败，可以分别尝试cordova prepare android , cordova prepare ios, cordova prepare browser，这样3个平台都尝试下，看看有哪个是有问题的

**Comment by beyonderyue** [comment]
cordova 我装了 7.1.0,还是这个错误，
不知道你的node和npm版本是多少？

Discovered platform "android@^6.2.3" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-android@^6.2.3
Error: Failed to fetch platform cordova-android@^6.2.3
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: npm: Command failed with exit code 254 Error output:
npm WARN checkPermissions Missing write access to /Users/mobilerover/Documents/GitHub/firefly/node_modules/configstore/node_modules/uuid
npm WARN checkPermissions Missing write access to /Users/mobilerover/Documents/GitHub/firefly/node_modules/got/node_modules/object-assign
npm WARN checkPermissions Missing write access to /Users/mobilerover/Documents/GitHub/firefly/node_modules/har-validator/node_modules/chalk
npm WARN checkPermissions Missing write access to /Users/mobilerover/Documents/GitHub/firefly/node_modules/xmlbuilder/node_modules/lodash
npm WARN checkPermissions Missing write access to /Users/mobilerover/Documents/GitHub/firefly/node_modules/xmlbuilder/node_modules
npm ERR! path /Users/mobilerover/Documents/GitHub/firefly/node_modules/configstore/node_modules/uuid
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/Users/mobilerover/Documents/GitHub/firefly/node_modules/configstore/node_modules/uuid'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mobilerover/.npm/_logs/2018-07-09T07_12_41_392Z-debug.log
Error: No platforms added to this project. Please use `cordova platform add <platform>`.

**Comment by beyonderyue** [comment]
问题依旧，，，打算放弃了，，，估计环境有啥问题
